### PR TITLE
Convert xml to UTF-8 explicitly to fix wrong encoding

### PR DESCRIPTION
**Pull request by vladzaets**
Fix `ArgumentError: invalid byte sequence in UTF-8`
https://app.honeybadger.io/projects/42520/faults/67779407

https://dekeo.atlassian.net/browse/CHARLIE-1622

### CODE REVIEW

**Review by alexeymetelev — APPROVED** [review]

**Comment by alexeymetelev** [comment]
@vladzaets can you provide some examples of real data? It would be good to see how it fixes the problem. Probably less risky is to just ignore this error in HB

**Comment by vladzaets** [comment]
@alexeymetelev you can try this: https://gist.github.com/vladzaets/ea65c1469b8d97b5d08cf0ec304c6c14
This is exactly what happens in `lib/savon/soap_fault.rb:8`

I've also suggested to contact supplier and ask to fix it on their side.

**Comment by alexeymetelev** [comment]
@vladzaets Ok it looks good, let's merge it

**Review by alexeymetelev — APPROVED** [review]
:+1:

**Pull request merged**
